#!/bin/bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG=$DIR/config.sh
if [ -f $CONFIG ]; then
    source $CONFIG
else
    echo "config file not found"
    exit 1
fi

netstat -ano | grep "$IP:$PORT" | awk '{print $5}' | {
    while IFS='' read -r line || [[ -n "$line" ]]; do
	PID=`echo $line | tr -d '\r'`
	(set -x; taskkill /PID $PID /F)
    done
}
